OPCODE_FORCE_UPDATE = 0x00
OPCODE_DECRYPT_N_SIGNATURE = 0x01
OPCODE_DECRYPT_SIGNATURE = 0x02
OPCODE_GET_SIGNATURE_TIMESTAMP = 0x03
OPCODE_PLAYER_STATUS = 0x04
OPCODE_PLAYER_UPDATE_TIMESTAMP = 0x05

PLAYER_UPDATED = 0xF44F
PLAYER_UPDATE_NOT_NEED = 0xFFFF
PLAYER_UPDATE_ERROR = 0x0000

VIDEO_ID = "IOWxtKoXHYo"

ENV_HOST = "HOST"
ENV_PORT = "PORT"

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 12999

LOG_LEVEL_DEFAULT = "INFO"
ENV_LOG_LEVEL = "LOG_LEVEL"

TCP_NODELAY_DEFAULT = "1"
ENV_TCP_NODELAY = "TCP_NODELAY"